#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2164

source /scripts/common

#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2025, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# Update JavaScript plugins on container start

export APPNAME="50-plugin-updates"

# Refresh bundled plugins on every start, including when remote updates are disabled.
# Keep custom plugins and back up changed files before replacing them.
mkdir -p /data/plugins || exit 1
set +o noglob
for file in /etc/AIS-catcher/plugins/*; do
    [[ -f "$file" ]] || continue
    destination="/data/plugins/${file##*/}"
    if ! cmp -s "$file" "$destination"; then
        cp --backup=numbered "$file" "$destination" || exit 1
        # The directory no longer represents the last downloaded Git commit.
        rm -f /data/plugins/.last_commit
    fi
done
set -o noglob

# Apply backup retention even when remote updates are disabled.
find /data/plugins -name '*.~*~' -mtime +"${BACKUP_RETENTION_TIME:-7}" -exec rm {} \;

#shellcheck disable=SC2076
if chk_disabled "${PLUGIN_UPDATE_INTERVAL,,}"; then
    s6wrap --quiet --timestamps --prepend="${APPNAME}" --args echo "Plugins Updating is disabled"
    exit 0
fi

exec /scripts/update-plugins init
