#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2164

source /scripts/common

#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2024, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# Back up the aiscatcher.bin file

# Copy plugin file if it's newer but leave a backup in place
if [[ -f /data/aiscatcher.bin ]]; then
  cp --backup=numbered -u /data/aiscatcher.bin /data/aiscatcher.bin.bkup
fi

# remove any backups older than BACKUP_RETENTION_TIME (or 30 days if undefined)
find /data -maxdepth 1 -name '*.~*~' -mtime +"${BACKUP_RETENTION_TIME:-30}" -exec rm {} \;
