#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2154

source /scripts/common

#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2025, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# Do some parameters housekeeping so both the new and the legacy params are supported:
FEEDER_LAT="${FEEDER_LAT:-$SXFEEDER_LAT}"
FEEDER_LONG="${FEEDER_LONG:-$SXFEEDER_LON}"

# check if logging is verbose:
if [[ -n "$VERBOSE_LOGGING" ]]
then
    [[ $VERBOSE_LOGGING =~ ^[0-5]{1}$ ]] && SHOWLOGS="-o $VERBOSE_LOGGING" || SHOWLOGS=""
else
    SHOWLOGS="-q -v 60"
fi

# Interpret additional feed targets, if defined
FEEDSTRING=()
if [[ -n "$UDP_FEEDS" ]]
then
    readarray -d "," -t feedsarray <<< "$UDP_FEEDS"
    for feeds in "${feedsarray[@]}"
    do
        [[ -n "$feeds" ]] && FEEDSTRING+=("-u ${feeds//:/ }")
    done
fi
if [[ -n "$TCP_FEEDS" ]]
then
    readarray -d "," -t feedsarray <<< "$TCP_FEEDS"
    for feeds in "${feedsarray[@]}"
    do
        [[ -n "$feeds" ]] && FEEDSTRING+=("-P ${feeds//:/ }")
    done
fi

# get gain
VALID_GAINS=(0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6)
# if the gain isn't defined, default to 33.8 (middle of the scale)
RTLSDR_DEVICE_GAIN="${RTLSDR_DEVICE_GAIN:-33.8}"
# if the gain isn't a number and it isn't "auto", then default to 33.8 (middle of the scale)
if [[ "${RTLSDR_DEVICE_GAIN,,}" != "auto" ]] && [[ ! $RTLSDR_DEVICE_GAIN =~ ^[+-]?[0-9.]+$ ]]
then
    RTLSDR_DEVICE_GAIN="33.8"
fi
# Now make sure that the gain is in the valid gains range, and if it isn't, pick the nearest higher one
# shellcheck disable=SC2076
if [[ ! " ${VALID_GAINS[*]} " =~ " ${RTLSDR_DEVICE_GAIN} " ]] && [[ "${RTLSDR_DEVICE_GAIN,,}" != "auto" ]]
then
    for GAIN in "${VALID_GAINS[@]}"
    do
        if [[ "$(awk "BEGIN {print int($GAIN * 10);}")" -ge "$(awk "BEGIN {print int($RTLSDR_DEVICE_GAIN * 10);}")" ]]
        then
            if [[ "$RTLSDR_DEVICE_GAIN" == "$GAIN" ]]; then
                "${s6wrap[@]}" echo "Gain set to ${RTLSDR_DEVICE_GAIN}"
            else
                "${s6wrap[@]}" echo "Gain ${RTLSDR_DEVICE_GAIN} rounded to ${GAIN}"
                RTLSDR_DEVICE_GAIN="$GAIN"
            fi
            break
        fi
    done
fi
# If the number is still larger than the largest allowed number, then default to that one
if [[ "$(awk "BEGIN {print int($RTLSDR_DEVICE_GAIN * 10);}")" -gt "$(awk "BEGIN {print int(${VALID_GAINS[-1]} * 10);}")" ]]; then 
    RTLSDR_DEVICE_GAIN="${VALID_GAINS[-1]}"
fi

# check if STATION_NAME and STATION_LINK is defined. If it is not, add the ShipXplorer URL
if [[ -z "$STATION_NAME" ]] && [[ -n "$SERIAL_NUMBER" ]]; then STATION_NAME="${SERIAL_NUMBER}"; fi
if [[ -z "$STATION_LINK" ]] && [[ -n "$SERIAL_NUMBER" ]]; then STATION_LINK="https://www.shipxplorer.com/stations/${SERIAL_NUMBER}"; fi

aiscatcher_command=()
aiscatcher_command+=("/usr/local/bin/AIS-catcher")
# set the web site parameters:
if ! chk_enabled "${DISABLE_WEBSITE}"; then
    aiscatcher_command+=("-N 80 FILE /data/aiscatcher.bin")
    if ! chk_enabled "${DISABLE_GEOJSON}"; then aiscatcher_command+=("GEOJSON on"); fi
    if chk_enabled "${DISABLE_SHIPSJSON_COMPRESS}"; then aiscatcher_command+=("ZLIB off"); fi
    if [[ -d "/data/plugins" ]]; then aiscatcher_command+=("PLUGIN_DIR /data/plugins"); fi
    if [[ -f "/data/about.md" ]]; then aiscatcher_command+=("ABOUT /data/about.md"); fi
    if [[ -n "${BACKUP_INTERVAL}" ]]; then aiscatcher_command+=("BACKUP ${BACKUP_INTERVAL}"); fi
    if [[ -n "${STATION_HISTORY}" ]]; then aiscatcher_command+=("HISTORY ${STATION_HISTORY}"); fi
    if chk_enabled "${PROMETHEUS_ENABLE}"; then aiscatcher_command+=("PROME on"); fi
    if [[ -n "${STATION_NAME}" ]]; then aiscatcher_command+=("STATION $STATION_NAME"); fi
    if [[ -n "${STATION_LINK}" ]]; then aiscatcher_command+=("STATION_LINK $STATION_LINK"); fi
    if [[ -n "$FEEDER_LAT" ]] && [[ -n "$FEEDER_LONG" ]]
    then
        aiscatcher_command+=("LAT $FEEDER_LAT LON $FEEDER_LONG")
        if chk_enabled "${SITESHOW}"; then aiscatcher_command+=("SHARE_LOC on"); fi
    fi
    if ! chk_enabled "${DISABLE_SHOWLASTMSG}"; then aiscatcher_command+=("MESSAGE on"); fi
    if chk_enabled "${REALTIME}"; then aiscatcher_command+=("REALTIME on"); fi
fi

# Add NMEA UDP inputs if needed:
if [[ -n "$AISCATCHER_UDP_INPUTS" ]]; then
    readarray -d "," -t feedsarray <<< "$AISCATCHER_UDP_INPUTS"
    for feeds in "${feedsarray[@]}"
    do
        if [[ -n "$feeds" ]]; then
            feeds="${feeds/:/ }"
            feeds="${feeds/:/ -c }"
            if ! grep -q "\-c" <<< "$feeds"; then
                feeds="$feeds -c AB"
            fi
            aiscatcher_command+=("-x ${feeds}")
        fi
    done
fi

# Add a number of well-known feeders: 
# ADSBNetwork / RadarVirtuel:
if [[ -n "${RADARVIRTUEL_STATION_ID}" ]]; then
    aiscatcher_command+=("-H https://ais.adsbnetwork.com/ingester/insert/${RADARVIRTUEL_FEEDER_KEY:-lourd} ID $RADARVIRTUEL_STATION_ID INTERVAL 15 RESPONSE off")
fi

# AirFrames:
if [[ -n "$AIRFRAMES_STATION_ID" ]]; then
    aiscatcher_command+=("-H http://feed.airframes.io:5599 ID $AIRFRAMES_STATION_ID INTERVAL 30 RESPONSE off")
fi

# AIS-Catcher:
if [[ -n "$AISCATCHER_FEEDER_KEY" ]] || chk_enabled "$AISCATCHER_SHAREDATA"; then
    aiscatcher_command+=("-X${AISCATCHER_FEEDER_KEY:+ }$AISCATCHER_FEEDER_KEY")
    AISCATCHER_EXTRA_OPTIONS="$(sed -E 's/-X\s+[0-9]*\s*//g'<<< "$AISCATCHER_EXTRA_OPTIONS")" # Remove any -X from param to avoid duplication
fi

# AIS Friends:
if [[ -n "$AISFRIENDS_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$AISFRIENDS_UDP_PORT"; then AISFRIENDS_UDP_PORT="ais.aisfriends.com:$AISFRIENDS_UDP_PORT"; fi
    aiscatcher_command+=("-u ${AISFRIENDS_UDP_PORT/:/ }")
fi
if [[ -n "$AISFRIENDS_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$AISFRIENDS_TCP_PORT"; then AISFRIENDS_TCP_PORT="ais.aisfriends.com:$AISFRIENDS_TCP_PORT"; fi
    aiscatcher_command+=("-P ${AISFRIENDS_TCP_PORT/:/ }")
fi
if [[ -n "$AISFRIENDS_UDP_PORT" ]] && [[ -n "$AISFRIENDS_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both AISFRIENDS_UDP_PORT and AISFRIENDS_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# AISHub:
if [[ -n "$AISHUB_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$AISHUB_UDP_PORT"; then AISHUB_UDP_PORT="data.aishub.net:$AISHUB_UDP_PORT"; fi
    aiscatcher_command+=("-u ${AISHUB_UDP_PORT/:/ }")
fi
if [[ -n "$AISHUB_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$AISHUB_TCP_PORT"; then AISHUB_TCP_PORT="data.aishub.net:$AISHUB_TCP_PORT"; fi
    aiscatcher_command+=("-P ${AISHUB_TCP_PORT/:/ }")
fi
if [[ -n "$AISHUB_UDP_PORT" ]] && [[ -n "$AISHUB_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both AISHUB_UDP_PORT and AISHUB_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# aprs.fi:
if [[ -n "${APRSFI_FEEDER_KEY:+$APRSFI_STATION_ID}" ]]; then
    aiscatcher_command+=("-H http://aprs.fi/jsonais/post/$APRSFI_FEEDER_KEY ID $APRSFI_STATION_ID PROTOCOL aprs INTERVAL 30 RESPONSE off")
fi

# BoatBeacon aka Pocket Mariner
if [[ -n "$BOATBEACON_UDP_PORT" ]]; then
    if ! grep -q ":"  <<< "$BOATBEACON_UDP_PORT"; then BOATBEACON_UDP_PORT="boatbeaconapp.com:$BOATBEACON_UDP_PORT"; fi
    aiscatcher_command+=("-u ${BOATBEACON_UDP_PORT/:/ }")
elif [[ -n "$BOATBEACON_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$BOATBEACON_TCP_PORT"; then BOATBEACON_TCP_PORT="data.aishub.net:$BOATBEACON_TCP_PORT"; fi
    aiscatcher_command+=("-P ${BOATBEACON_TCP_PORT/:/ }")
elif chk_enabled "$BOATBEACON_SHAREDATA"; then
    aiscatcher_command+=("-u boatbeaconapp.com 5322")
fi

if [[ -n "$BOATBEACON_UDP_PORT" ]] && [[ -n "$BOATBEACON_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both BOATBEACON_UDP_PORT and BOATBEACON_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# HPRadar:
if [[ -n "$HPRADAR_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$HPRADAR_UDP_PORT"; then HPRADAR_UDP_PORT="aisfeed.hpradar.com:$HPRADAR_UDP_PORT"; fi
    aiscatcher_command+=("-u ${HPRADAR_UDP_PORT/:/ } JSON on")
fi
if [[ -n "$HPRADAR_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$HPRADAR_TCP_PORT"; then HPRADAR_TCP_PORT="data.aishub.net:$HPRADAR_TCP_PORT"; fi
    aiscatcher_command+=("-P ${HPRADAR_TCP_PORT/:/ }")
fi
if [[ -n "$HPRADAR_UDP_PORT" ]] && [[ -n "$HPRADAR_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both HPRADAR_UDP_PORT and HPRADAR_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# MarineTraffic:
if [[ -n "$MARINETRAFFIC_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$MARINETRAFFIC_UDP_PORT"; then MARINETRAFFIC_UDP_PORT="5.9.207.224:$MARINETRAFFIC_UDP_PORT"; fi
    aiscatcher_command+=("-u ${MARINETRAFFIC_UDP_PORT/:/ }")
fi
if [[ -n "$MARINETRAFFIC_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$MARINETRAFFIC_TCP_PORT"; then MARINETRAFFIC_TCP_PORT="5.9.207.224:$MARINETRAFFIC_TCP_PORT"; fi
    aiscatcher_command+=("-P ${MARINETRAFFIC_TCP_PORT/:/ }")
fi
if [[ -n "$MARINETRAFFIC_UDP_PORT" ]] && [[ -n "$MARINETRAFFIC_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both MARINETRAFFIC_UDP_PORT and MARINETRAFFIC_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# MyShipTracking:
MYSHIPTRACKING_UDP_PORT="${MYSHIPTRACKING_UDP_PORT:-$MYSHIPTRACKER_UDP_PORT}" # bug fix - originally wrote wrongly MYSHIPTRACKER_UDP_PORT, now we need to keep this for backward compatibility
if [[ -n "$MYSHIPTRACKING_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$MYSHIPTRACKING_UDP_PORT"; then MYSHIPTRACKING_UDP_PORT="178.162.215.175:$MYSHIPTRACKING_UDP_PORT"; fi
    aiscatcher_command+=("-u ${MYSHIPTRACKING_UDP_PORT/:/ }")
fi
if [[ -n "$MYSHIPTRACKING_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$MYSHIPTRACKING_TCP_PORT"; then MYSHIPTRACKING_TCP_PORT="178.162.215.175:$MYSHIPTRACKING_TCP_PORT"; fi
    aiscatcher_command+=("-P ${MYSHIPTRACKING_TCP_PORT/:/ }")
fi
if [[ -n "$MYSHIPTRACKING_UDP_PORT" ]] && [[ -n "$MYSHIPTRACKING_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both MYSHIPTRACKING_UDP_PORT and MYSHIPTRACKING_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# SDRMap:
if [[ -n "${SDRMAP_PASSWORD:+$SDRMAP_STATION_ID}" ]]; then
    aiscatcher_command+=("-H https://ais.feed.sdrmap.org/ USERPWD ${SDRMAP_STATION_ID}:${SDRMAP_PASSWORD} GZIP on INTERVAL 15 RESPONSE off")
fi

# ShippingExplorer:
if [[ -n "$SHIPPINGEXPLORER_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$SHIPPINGEXPLORER_UDP_PORT"; then SHIPPINGEXPLORER_UDP_PORT="144.76.54.111:$SHIPPINGEXPLORER_UDP_PORT"; fi
    aiscatcher_command+=("-u ${SHIPPINGEXPLORER_UDP_PORT/:/ }")
fi
if [[ -n "$SHIPPINGEXPLORER_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$SHIPPINGEXPLORER_TCP_PORT"; then SHIPPINGEXPLORER_TCP_PORT="178.162.215.175:$SHIPPINGEXPLORER_TCP_PORT"; fi
    aiscatcher_command+=("-P ${SHIPPINGEXPLORER_TCP_PORT/:/ }")
fi
if [[ -n "$SHIPPINGEXPLORER_UDP_PORT" ]] && [[ -n "$SHIPPINGEXPLORER_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both SHIPPINGEXPLORER_UDP_PORT and SHIPPINGEXPLORER_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# ShipFinder:
if [[ -n "$SHIPFINDER_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$SHIPFINDER_UDP_PORT"; then SHIPFINDER_UDP_PORT="ais.shipfinder.co.uk:$SHIPFINDER_UDP_PORT"; fi
    aiscatcher_command+=("-u ${SHIPFINDER_UDP_PORT/:/ }")
elif chk_enabled "$SHIPFINDER_SHAREDATA"; then
    aiscatcher_command+=("-u ais.shipfinder.co.uk 4001")
fi
if [[ -n "$SHIPFINDER_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$SHIPFINDER_TCP_PORT"; then SHIPFINDER_TCP_PORT="178.162.215.175:$SHIPFINDER_TCP_PORT"; fi
    aiscatcher_command+=("-P ${SHIPFINDER_TCP_PORT/:/ }")
fi
if [[ -n "$SHIPFINDER_UDP_PORT" ]] && [[ -n "$SHIPFINDER_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both SHIPFINDER_UDP_PORT and SHIPFINDER_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi
if [[ -n "$SHIPFINDER_SHAREDATA" ]] && [[ -n "$SHIPFINDER_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both SHIPFINDER_SHAREDATA and SHIPFINDER_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# ShipXplorer UDP feed (can be used as an alternative for feeding with sxfeeder):
if [[ -n "$SHIPXPLORER_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$SHIPXPLORER_UDP_PORT"; then SHIPXPLORER_UDP_PORT="hub.shipxplorer.com:$SHIPXPLORER_UDP_PORT"; fi
    aiscatcher_command+=("-u ${SHIPXPLORER_UDP_PORT/:/ }")
fi
if [[ -n "${SHARING_KEY:-${SX_SHARING_KEY:-${SHIPXPLORER_SHARING_KEY}}}${SERIAL_NUMBER:-${SX_SERIAL_NUMBER:-${SHIPXPLORER_SERIAL_NUMBER}}}" ]] && [[ -n "$SHIPXPLORER_UDP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both [SHIPXPLORER_]SHARING_KEY/[SHIPXPLORER_]SERIAL_NUMBER and SHIPXPLORER_UDP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# VesselFinder:
if [[ -n "$VESSELFINDER_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$VESSELFINDER_UDP_PORT"; then VESSELFINDER_UDP_PORT="ais.vesselfinder.com:$VESSELFINDER_UDP_PORT"; fi
    aiscatcher_command+=("-u ${VESSELFINDER_UDP_PORT/:/ }")
fi
if [[ -n "$VESSELFINDER_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$VESSELFINDER_TCP_PORT"; then VESSELFINDER_TCP_PORT="178.162.215.175:$VESSELFINDER_TCP_PORT"; fi
    aiscatcher_command+=("-P $VESSELFINDER_TCP_PORT/:/ }")
fi
if [[ -n "$VESSELFINDER_UDP_PORT" ]] && [[ -n "$VESSELFINDER_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both VESSELFINDER_UDP_PORT and VESSELFINDER_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

# VesselTracker:
if [[ -n "$VESSELTRACKER_UDP_PORT" ]]; then
    if ! grep -q ":" <<< "$VESSELTRACKER_UDP_PORT"; then VESSELTRACKER_UDP_PORT="83.220.137.136:$VESSELTRACKER_UDP_PORT"; fi
    aiscatcher_command+=("-u ${VESSELTRACKER_UDP_PORT/:/ }")
fi
if [[ -n "$VESSELTRACKER_TCP_PORT" ]]; then
    if ! grep -q ":" <<< "$VESSELTRACKER_TCP_PORT"; then VESSELTRACKER_TCP_PORT="83.220.137.136:$VESSELTRACKER_TCP_PORT"; fi
    aiscatcher_command+=("-P ${VESSELTRACKER_TCP_PORT/:/ }")
fi
if [[ -n "$VESSELTRACKER_UDP_PORT" ]] && [[ -n "$VESSELTRACKER_TCP_PORT" ]]; then
    "${s6wrap[@]}" echo "[WARNING] Both VESSELTRACKER_UDP_PORT and VESSELTRACKER_TCP_PORT are defined. This may cause duplicate feeding to this aggregator. Please remove one of these from your environment!"
fi

aiscatcher_command+=("${FEEDSTRING[*]}")
aiscatcher_command+=("-u 127.0.0.1 34994")
aiscatcher_command+=("-u 127.0.0.1 34995")
aiscatcher_command+=("$SHOWLOGS")
if [[ -n "${RTLSDR_DEVICE_SERIAL}" ]]; then 
    AISCATCHER_CHANNELS="${AISCATCHER_CHANNELS^^}"; aiscatcher_command+=("-c ${AISCATCHER_CHANNELS:-AB}")
    #AISCATCHER_EXTRA_OPTIONS="$(sed -E 's/-c\s+[a-dA-D ]+//g' <<< "$AISCATCHER_EXTRA_OPTIONS")"   # remove any -c items from param to avoid duplication
    aiscatcher_command+=("-d ${RTLSDR_DEVICE_SERIAL}")
    aiscatcher_command+=("-gr tuner ${RTLSDR_DEVICE_GAIN}")
    if ! chk_disabled "${RTLSDR_DEVICE_RTLAGC}"; then
        aiscatcher_command+=("rtlagc ON")
    else
        aiscatcher_command+=("rtlagc OFF")
    fi
    if chk_enabled "${RTLSDR_DEVICE_BIASTEE}"; then
        aiscatcher_command+=("BIASTEE on")
    fi
    if [[ -n "${RTLSDR_DEVICE_PPM}" ]]; then
        aiscatcher_command+=("-p ${RTLSDR_DEVICE_PPM}")
        #AISCATCHER_EXTRA_OPTIONS="$(sed -E 's/-p\s+[0-9]+\s*//g'<<< "$AISCATCHER_EXTRA_OPTIONS")"   # remove any -p items from param to avoid duplication
    fi
    if [[ -n "${RTLSDR_DEVICE_BANDWIDTH}" ]]; then
        aiscatcher_command+=("-a ${RTLSDR_DEVICE_BANDWIDTH}")
        #AISCATCHER_EXTRA_OPTIONS="$(sed -E 's/-a\s+[0-9]+[A-Za-z]{1}\s*//g'<<< "$AISCATCHER_EXTRA_OPTIONS")"   # remove any -a items from param to avoid duplication
    elif ! grep -qoE '\-a\s+[0-9]+[A-Za-z]{1}' <<< "$AISCATCHER_EXTRA_OPTIONS"; then
        aiscatcher_command+=("-a 192K")
    fi
    if [[ -n "${AISCATCHER_DECODER_MODEL}" ]]; then
        aiscatcher_command+=("-m ${AISCATCHER_DECODER_MODEL}")
    fi
    if [[ -n "$AISCATCHER_DECODER_AFC_WIDE$AISCATCHER_DECODER_FP_DS$AISCATCHER_DECODER_PS_EMA$AISCATCHER_DECODER_SOXR$AISCATCHER_DECODER_SRC$AISCATCHER_DECODER_DROOP" ]]; then
        aiscatcher_command+=("-go")
        if chk_enabled "$AISCATCHER_DECODER_AFC_WIDE" || \
           { [[ -z "$AISCATCHER_DECODER_AFC_WIDE" ]] && ! grep -qi 'AFC_WIDE' <<< "$AISCATCHER_EXTRA_OPTIONS"; }; then
                aiscatcher_command+=("AFC_WIDE on")
        fi
        if chk_disabled "$AISCATCHER_DECODER_AFC_WIDE"; then aiscatcher_command+=("AFC_WIDE off"); fi
        if chk_enabled "$AISCATCHER_DECODER_FP_DS"; then aiscatcher_command+=("FP_DS on"); fi
        if chk_disabled "$AISCATCHER_DECODER_FP_DS"; then aiscatcher_command+=("FP_DS off"); fi
        if chk_enabled "$AISCATCHER_DECODER_PS_EMA"; then aiscatcher_command+=("PS_EMA on"); fi
        if chk_disabled "$AISCATCHER_DECODER_PS_EMA"; then aiscatcher_command+=("PS_EMA off"); fi
        if chk_enabled "$AISCATCHER_DECODER_SOXR"; then aiscatcher_command+=("SOXR on"); fi
        if chk_disabled "$AISCATCHER_DECODER_SOXR"; then aiscatcher_command+=("SOXR off"); fi
        if chk_enabled "$AISCATCHER_DECODER_SRC"; then aiscatcher_command+=("SRC on"); fi
        if chk_disabled "$AISCATCHER_DECODER_SRC"; then aiscatcher_command+=("SRC off"); fi
        if chk_enabled "$AISCATCHER_DECODER_DROOP"; then aiscatcher_command+=("DROOP on"); fi
        if chk_disabled "$AISCATCHER_DECODER_DROOP"; then aiscatcher_command+=("DROOP off"); fi
    elif [[ -z "$AISCATCHER_DECODER_AFC_WIDE" ]] && ! grep -qi 'AFC_WIDE' <<< "$AISCATCHER_EXTRA_OPTIONS"; then
        aiscatcher_command+=("-go AFC_WIDE on")
    fi
fi

if [[ -n "${AISCATCHER_MQTT_URL}" ]]; then
    aiscatcher_command+=("-Q ${AISCATCHER_MQTT_URL}")
    if [[ -n "${AISCATCHER_MQTT_CLIENT_ID}" ]]; then aiscatcher_command+=("CLIENT_ID ${AISCATCHER_MQTT_CLIENT_ID}"); fi
    if [[ -n "${AISCATCHER_MQTT_QOS}" ]]; then aiscatcher_command+=("QOS ${AISCATCHER_MQTT_QOS}"); fi
    if [[ -n "${AISCATCHER_MQTT_TOPIC}" ]]; then aiscatcher_command+=("TOPIC ${AISCATCHER_MQTT_TOPIC}"); fi
    aiscatcher_command+=("MSGFORMAT ${AISCATCHER_MQTT_MSGFORMAT:-JSON_FULL}")
fi

if [[ -n "$ADSB_CONNECTOR" ]]; then
    readarray -d, -t connector <<< "$ADSB_CONNECTOR"
    aiscatcher_command+=("-t ${connector[0]//$'\n'/} ${connector[1]//$'\n'/} ${connector[2]//$'\n'/}")
    if [[ -n "$FEEDER_LAT" ]] && [[ -n "$FEEDER_LONG" ]]; then
        aiscatcher_command+=("-Z $FEEDER_LAT $FEEDER_LONG")
    fi
fi

aiscatcher_command+=("$AISCATCHER_EXTRA_OPTIONS")

# shellcheck disable=SC2068
aiscommand="$(echo ${aiscatcher_command[@]} | xargs)"

"${s6wrap[@]}" echo "Starting: ${aiscommand}"

# shellcheck disable=SC2048
# shellcheck disable=SC2086
exec "${s6wrap[@]}" ${aiscommand}
