#!/usr/bin/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC2016,SC2068,SC2086


# check if logging is verbose:
[[ -n "$VERBOSE_LOGGING" ]] && SHOWLOGS="" || SHOWLOGS="-q"

# Interpret additional feed targets, if defined
FEEDSTRING=()
if [[ -n "$UDP_FEEDS" ]]
then
    readarray -d "," -t feedsarray <<< "$UDP_FEEDS"
    for feeds in "${feedsarray[@]}"
    do
        [[ -n "$feeds" ]] && FEEDSTRING+=("-u ${feeds/:/ }")
    done
fi

# get gain
[[ -x "$RTLSDR_DEVICE_GAIN" ]] && RTLSDR_DEVICE_GAIN="33.3"

# Test AIS-catcher can run natively (without qemu)
if /usr/bin/AIS-catcher -h > /dev/null 2>&1
then
    # can be run natively
    /usr/bin/AIS-catcher $AISCATCHER_EXTRA_OPTIONS -u 127.0.0.1 34995 ${FEEDSTRING[@]} $SHOWLOGS -d "${RTLSDR_DEVICE_SERIAL}" -gr tuner "${RTLSDR_DEVICE_GAIN}" rtlagc ON 2>&1 | \
        stdbuf -oL awk '{print "[aiscatcher] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    # needs qemu
    qemu-arm-static /usr/bin/AIS-catcher $AISCATCHER_EXTRA_OPTIONS -u 127.0.0.1 34995 ${FEEDSTRING[@]} -u 127.0.0.1 34996 $SHOWLOGS -d "${RTLSDR_DEVICE_SERIAL}" -gr tuner "${RTLSDR_DEVICE_GAIN}" rtlagc ON 2>&1 | \
        stdbuf -oL awk '{print "[aiscatcher] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi
