#!/usr/bin/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC2016,SC2068,SC2076,SC2086


# check if logging is verbose:
if [[ -n "$VERBOSE_LOGGING" ]]
then
    [[ $VERBOSE_LOGGING =~ ^[0-5]{1}$ ]] && SHOWLOGS="-o $VERBOSE_LOGGING" || SHOWLOGS=""
else
    SHOWLOGS="-q -v 60"
fi

# Interpret additional feed targets, if defined
FEEDSTRING=()
if [[ -n "$UDP_FEEDS" ]]
then
    readarray -d "," -t feedsarray <<< "$UDP_FEEDS"
    for feeds in "${feedsarray[@]}"
    do
        [[ -n "$feeds" ]] && FEEDSTRING+=("-u ${feeds/:/ }")
    done
fi

# get gain
VALID_GAINS=(0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6)
# if the gain isn't defined, default to 33.8 (middle of the scale)
[[ -x "$RTLSDR_DEVICE_GAIN" ]] && RTLSDR_DEVICE_GAIN="33.8"
# if the gain isn't a number and it isn't "auto", then default to 33.8 (middle of the scale)
if [[ "$RTLSDR_DEVICE_GAIN" != "auto" ]] && [[ ! $RTLSDR_DEVICE_GAIN =~ ^[+-]?[0-9.]+$ ]]
then
    RTLSDR_DEVICE_GAIN="33.8"
fi
# Now make sure that the gain is in the valid gains range, and if it isn't, pick the nearest higher one
if [[ ! " ${VALID_GAINS[*]} " =~ " ${RTLSDR_DEVICE_GAIN} " ]]
then
    for GAIN in "${VALID_GAINS[@]}"
    do
        if [[ "$(awk "BEGIN {print int($GAIN * 10);}")" -ge "$(awk "BEGIN {print int($RTLSDR_DEVICE_GAIN * 10);}")" ]]
        then
            RTLSDR_DEVICE_GAIN="$GAIN"
            echo "[aiscatcher][$(date +"%Y/%m/%d %H:%M:%S")] Gain rounded to ${RTLSDR_DEVICE_GAIN}"
            break
        fi
    done
fi
# If the number is still larger than the largest allowed number, then default to that one
[[ "$(awk "BEGIN {print int($RTLSDR_DEVICE_GAIN * 10);}")" -gt "$(awk "BEGIN {print int(${VALID_GAINS[-1]} * 10);}")" ]] && RTLSDR_DEVICE_GAIN="${VALID_GAINS[-1]}"

aiscatcher_command="/usr/local/bin/AIS-catcher -u 127.0.0.1 34995 ${FEEDSTRING[*]} $SHOWLOGS -d ${RTLSDR_DEVICE_SERIAL} -gr tuner ${RTLSDR_DEVICE_GAIN} rtlagc ON $AISCATCHER_EXTRA_OPTIONS"
echo "[aiscatcher][$(date +"%Y/%m/%d %H:%M:%S")] Starting: $aiscatcher_command"

# Test AIS-catcher can run natively (without qemu)
if /usr/local/bin/AIS-catcher -h > /dev/null 2>&1
then
    # can be run natively
    $aiscatcher_command 2>&1 | \
        stdbuf -oL awk '{print "[aiscatcher][" strftime("%Y/%m/%d %H:%M:%S", systime()) "] " $0}'
else
    # needs qemu
    qemu-arm-static $aiscatcher_command 2>&1 | \
        stdbuf -oL awk '{print "[aiscatcher][" strftime("%Y/%m/%d %H:%M:%S", systime()) "] " $0}'
fi
