#!/usr/bin/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC2016


# Wait for AIS-atcher to be up and running
while ! pgrep AIS-catcher >/dev/null 2>&1
do
    sleep 1
done

# Give AIS-catcher a bit of time to establish the connection to the SDR:
sleep 5

/usr/bin/sxfeeder 2>&1 | \
    stdbuf -oL awk '{print "[sxfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
