#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2016,SC2068,SC2076,SC2086,SC2015

source /scripts/common
APPNAME="aiscatcher"
s6wrap=(s6wrap --quiet --timestamps --prepend="${APPNAME}")

#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------


# check if logging is verbose:
if [[ -n "$VERBOSE_LOGGING" ]]
then
    [[ $VERBOSE_LOGGING =~ ^[0-5]{1}$ ]] && SHOWLOGS="-o $VERBOSE_LOGGING" || SHOWLOGS=""
else
    SHOWLOGS="-q -v 60"
fi

# Interpret additional feed targets, if defined
FEEDSTRING=()
if [[ -n "$UDP_FEEDS" ]]
then
    readarray -d "," -t feedsarray <<< "$UDP_FEEDS"
    for feeds in "${feedsarray[@]}"
    do
        [[ -n "$feeds" ]] && FEEDSTRING+=("-u ${feeds//:/ }")
    done
fi

# get gain
VALID_GAINS=(0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6)
# if the gain isn't defined, default to 33.8 (middle of the scale)
RTLSDR_DEVICE_GAIN="${RTLSDR_DEVICE_GAIN:-33.8}"
# if the gain isn't a number and it isn't "auto", then default to 33.8 (middle of the scale)
if [[ "${RTLSDR_DEVICE_GAIN,,}" != "auto" ]] && [[ ! $RTLSDR_DEVICE_GAIN =~ ^[+-]?[0-9.]+$ ]]
then
    RTLSDR_DEVICE_GAIN="33.8"
fi
# Now make sure that the gain is in the valid gains range, and if it isn't, pick the nearest higher one
if [[ ! " ${VALID_GAINS[*]} " =~ " ${RTLSDR_DEVICE_GAIN} " ]] && [[ "${RTLSDR_DEVICE_GAIN,,}" != "auto" ]]
then
    for GAIN in "${VALID_GAINS[@]}"
    do
        if [[ "$(awk "BEGIN {print int($GAIN * 10);}")" -ge "$(awk "BEGIN {print int($RTLSDR_DEVICE_GAIN * 10);}")" ]]
        then
            RTLSDR_DEVICE_GAIN="$GAIN"
            "${s6wrap[@]}" --args echo "Gain rounded to ${RTLSDR_DEVICE_GAIN}"
            break
        fi
    done
fi
# If the number is still larger than the largest allowed number, then default to that one
[[ "$(awk "BEGIN {print int($RTLSDR_DEVICE_GAIN * 10);}")" -gt "$(awk "BEGIN {print int(${VALID_GAINS[-1]} * 10);}")" ]] && RTLSDR_DEVICE_GAIN="${VALID_GAINS[-1]}"

# check if STATION_NAME and STATION_LINK is defined. If it is not, add the ShipXplorer URL
[[ -z "$STATION_NAME" ]] && [[ -n "$SERIAL_NUMBER" ]] && STATION_NAME="${SERIAL_NUMBER}" || true
[[ -z "$STATION_LINK" ]] && [[ -n "$SERIAL_NUMBER" ]] && STATION_LINK="https://www.shipxplorer.com/stations/${SERIAL_NUMBER}" || true

aiscatcher_command=()
aiscatcher_command+=("/usr/local/bin/AIS-catcher")
# set the web site parameters:
if ! chk_enabled "${DISABLE_WEBSITE}"; then
    aiscatcher_command+=("-N 80 REUSE_PORT on FILE /data/aiscatcher.bin")
    chk_enabled "${DISABLE_SHIPSJSON_COMPRESS}" && aiscatcher_command+=("ZLIB off") || true
    [[ -d "/data/plugins" ]] && aiscatcher_command+=("PLUGIN_DIR /data/plugins") || true
    [[ -f "/data/about.md" ]] && aiscatcher_command+=("ABOUT /data/about.md") || true
    [[ -n "${BACKUP_INTERVAL}" ]] && aiscatcher_command+=("BACKUP ${BACKUP_INTERVAL}") || true
    [[ -n "${STATION_HISTORY}" ]] && aiscatcher_command+=("HISTORY ${STATION_HISTORY}") || true
    chk_enabled "${PROMETHEUS_ENABLE}" && aiscatcher_command+=("PROME on") || true
    [[ -n "${STATION_NAME}" ]] && aiscatcher_command+=("STATION $STATION_NAME") || true
    [[ -n "${STATION_LINK}" ]] && aiscatcher_command+=("STATION_LINK $STATION_LINK") || true
    if [[ -n "$SXFEEDER_LAT" ]] && [[ -n "$SXFEEDER_LON" ]]
    then
        aiscatcher_command+=("LAT $SXFEEDER_LAT LON $SXFEEDER_LON")
        chk_enabled "${SITESHOW}" && aiscatcher_command+=("SHARE_LOC on") || true
    fi
    chk_enabled "${DISABLE_SHOWLASTMSG}" && true || aiscatcher_command+=("MESSAGE on")
    chk_enabled "${REALTIME}" && aiscatcher_command+=("REALTIME on") || true
fi
aiscatcher_command+=("-u 127.0.0.1 34994")
aiscatcher_command+=("-u 127.0.0.1 34995")
aiscatcher_command+=("${FEEDSTRING[*]}")
aiscatcher_command+=("$SHOWLOGS")
[[ -n "${RTLSDR_DEVICE_SERIAL}" ]] && aiscatcher_command+=("-d ${RTLSDR_DEVICE_SERIAL}") || true
[[ -n "${RTLSDR_DEVICE_SERIAL}" ]] && aiscatcher_command+=("-gr tuner ${RTLSDR_DEVICE_GAIN} rtlagc ON")
aiscatcher_command+=("$AISCATCHER_EXTRA_OPTIONS")

aiscommand="$(echo ${aiscatcher_command[@]} | xargs)"

"${s6wrap[@]}" --args echo "Starting: ${aiscommand}"

# shellcheck disable=SC2048
exec "${s6wrap[@]}" --args ${aiscommand}
