#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2164

source /scripts/common

#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# Update JavaScript plugins on container start

export APPNAME="50-plugin-updates"

#shellcheck disable=SC2076
if chk_disabled "${PLUGIN_UPDATE_INTERVAL,,}"; then
    s6wrap --quiet --timestamps --prepend="${APPNAME}" --args echo "Plugins Updating is disabled"
    exit 0
fi

exec /scripts/update-plugins
