#!/usr/bin/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC2016

if [ "$VERBOSE_LOGGING" == "true" ]; then
    /usr/bin/sxfeeder 2>&1 | \
    stdbuf -oL awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    /usr/bin/sxfeeder 2>&1 | \
    stdbuf -oL awk '! / Statistics updated every 30 seconds /' | \
    stdbuf -oL awk '! /Packets sent in the last 30 seconds: /' | \
    stdbuf -oL awk '! / Data sent: /' | \
    stdbuf -oL awk '! / Data received: /' | \
    stdbuf -oL awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi
