#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2164

source /scripts/common

#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# Update JavaScript plugins

APPNAME="$0"

if ! chk_enabled "${UPDATE_PLUGINS}"
then
  echo "[$(date)][${APPNAME}] UPDATE_PLUGINS is not set to true; skipping plugin updates"
  exit 0
fi

cd /tmp
if ! git clone --depth=1 https://github.com/jvde-github/AIS-catcher >/dev/null 2>&1
then
  echo "[$(date)][${APPNAME}] Couldn't clone AIS-catcher github - abandoning effort to update plugins"
  exit 0
fi

mkdir -p /data/plugins

pushd AIS-catcher >/dev/null 2>&1
  touch /data/plugins/.last_commit
  read -r last_commit < "/data/plugins/.last_commit"
  remote_last_commit="$(git log --pretty=format:"%h")"
  if [[  "${remote_last_commit}" == "${last_commit}" ]]
  then
    echo "[$(date)][${APPNAME}] Plugins haven't changed on remote repository - no need to update"
    popd  >/dev/null 2>&1
    rm -rf /tmp/AIS-catcher
    exit 0
  fi
  echo  "${remote_last_commit}" > "/data/plugins/.last_commit"
popd >/dev/null 2>&1

echo -n "[$(date)][${APPNAME}] Plugins need updating... "

if [[ -n "${last_commit}" ]]
then
  set +o noglob
  for file in /tmp/AIS-catcher/plugins/*
  do
    file="${file##*/}"
    if [[  -f /data/plugins/${file} ]] && ! diff "${file}" "/data/plugins/${file}" >/dev/null 2>&1
    then
      # Copy plugin file if it's newer but leave a backup in place
      cp --backup=numbered -u "/tmp/AIS-catcher/plugins/${file}" "/data/plugins/${file}"
    fi
  done
  set -o noglob
else
  # This is the first time - let's add all plugins from the repo but don't overwrite any existing files
  cp -n /tmp/AIS-catcher/plugins/* /data/plugins/ >/dev/null 2>&1
fi

rm -rf /tmp/AIS-catcher

echo "[$(date)][${APPNAME}] done!"
