#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC2164

#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# Update JavaScript plugins

APPNAME="$0"

if [[ "${UPDATE_PLUGINS}" != true ]]
then
  echo "[$(date)][${APPNAME}] UPDATE_PLUGINS is not set to true; skipping plugin updates"
  exit 0
fi

cd /tmp
if ! git clone --depth=1 https://github.com/jvde-github/AIS-catcher >/dev/null 2>&1
then
  echo "[$(date)][${APPNAME}] Couldn't clone AIS-catcher github - abandoning effort to update plugins"
  exit 0
fi

cd AIS-catcher
touch /data/plugins/.last_commit
read -r last_commit < "/data/plugins/.last_commit"
remote_last_commit="$(git log --pretty=format:"%h")"
if [[  "${remote_last_commit}" == "${last_commit}" ]]
then
  echo "[$(date)][${APPNAME}] Plugins haven't changed on remote repository - no need to update"
  cd /
  rm -rf /tmp/AIS-catcher
  exit 0
fi
echo  "${remote_last_commit}" > "/data/plugins/.last_commit"
cd /
echo -n "[$(date)][${APPNAME}] Plugins need updating... "

set +o noglob
for file in "/tmp/AIS-catcher/plugins/*"
do
  file="${file##*/}"
  if [[  -f /data/plugins/${file} ]]
  then
    # Copy plugin file if it's newer but leave a backup in place
    cp --backup=numbered -u "/tmp/AIS-catcher/plugins/${file}" "/data/plugins/{file}"
  fi
done
set -o noglob
rm -rf /tmp/AIS-catcher

echo "done!"
